#	  _____       _ _ _                 _     
#	 / ____|     (_) | |               | |  _ 
#	| (___   __ _ _| | |__   ___   __ _| |_(_)
#	 \___ \ / _` | | | '_ \ / _ \ / _` | __|  
#	 ____) | (_| | | | |_) | (_) | (_| | |_ _ 
#	|_____/ \__,_|_|_|_.__/ \___/ \__,_|\__(_)
                                          
# Basic Setup:
name = "Sailboat"
short_name = "sailboat"
email = "cole@colewilson.xyz"
short_description = "🐍 A quick and easy way to distribute your Python projects!"
description = ""
url = "https://github.com/cole-wilson/sailboat"
keywords = ""
license = "MIT"
latest_build = "0.12.5"
author = "Cole Wilson"
latest_release = "0.12.4"
release-notes = "."


# Resource Setup:
[resources]
icon = ""
data_files = [ "resources/*", "plugins.json",]
modules = [ "toml", "semver", "requests", "setuptools", "pathlib",]
file = "__main__.py"
no_import = [ "shutil", "re", "os", "glob", "pkg_resources", "traceback", "json",]


# Plugin Commands:
[command.tasks]

[command.actions]
mac = true
windows = true
linux = true


# Build Routines:
[build.homebrew]

[build.pyinstaller]
_run = false
type = 1
mac = true
windows = true
unix = true
bundle_id = "xyz.colewilson.sailboat"

[build.pypi.commands]
sail = "__main__.main"
sailboat = "__main__.main"

[build.pypi.entry_points.sailboat_plugins]
pypi = "sailboat.builders:PyPi"
homebrew = "sailboat.builders:Homebrew"
echo = "sailboat.__main__:echo"
pyinstaller = "sailboat.builders:PyInstaller"
dev = "sailboat.core:Develop"
release = "sailboat.core:Release"
build = "sailboat.build:Build"
wizard = "sailboat.core:Wizard"
remove = "sailboat.core:Remove"
add = "sailboat.core:Add"
plugins = "sailboat.core:ManagePlugins"
test = "sailboat.tests:Test"
git = "sailboat.core:Git"
tasks = "sailboat.other:Tasks"
workflow = "sailboat.core:Actions"
github = "sailboat.core:GitHub"


# Release Routines:
[release.echo]
int = 1

[release.github]


# Other:
[git]
brew = "cole-wilson/homebrew-taps"
github = "cole-wilson/sailboat"


# Thank you for using Sailboat!