#            _  _  _                _   
#  ___ __ _ (_)| || |__  ___  __ _ | |_ 
# (_-</ _` || || || '_ \/ _ \/ _` ||  _|
# /__/\__,_||_||_||_.__/\___/\__,_| \__|
                                      
# Basic Setup:
_comments = true
name = "Sailboat"
short_name = "sailboat"
email = "cole@colewilson.xyz"
short_description = "A quick and easy way to distribute your Python projects!"
description = ""
url = "https://github.com/cole-wilson/sailboat"
keywords = ""
license = "MIT"
latest_build = "0.24.7+7d6418d.10"
author = "Cole Wilson"
latest_release = "0.24.5-rc.2"
release-notes = "a"


# Resource Setup:
[resources]
icon = ""
data_files = [ "resources/*", "plugins.json", "autocomplete", "auto.bash",]
modules = [ "toml", "semver", "requests", "setuptools", "twine",]
file = "__main__.py"
no_import = [ "shutil", "pathlib", "re", "os", "glob", "pkg_resources", "traceback", "json", "subprocess",]


# Plugin Commands:
[command.tasks]


# Build Routines:
[build.homebrew]

[build.pyinstaller]
_run = false
type = 1
mac = true
windows = true
unix = true
bundle_id = "xyz.colewilson.sailboat"

[build.build_docs_readme]

[build.setcodeversion]

[build.pypi.commands]
sail = "__main__.main"
sailboat = "__main__.main"

[build.pypi.entry_points.sailboat_plugins]
quickstart = "sailboat.core:QuickStart"
pypi = "sailboat.builders:PyPi"
homebrew = "sailboat.builders:Homebrew"
pyinstaller = "sailboat.builders:PyInstaller"
dev = "sailboat.core:Develop"
release = "sailboat.core:Release"
build = "sailboat.build:Build"
wizard = "sailboat.core:Wizard"
remove = "sailboat.core:Remove"
add = "sailboat.core:Add"
plugins = "sailboat.core:ManagePlugins"
git = "sailboat.core:Git"
tasks = "sailboat.other:Tasks"
workflow = "sailboat.core:Actions"
github = "sailboat.core:Git"
github_release = "sailboat.core:GithubRelease"
build_docs_readme = "sailboat.other:BuildDocs"
setcodeversion = "sailboat.other:SetVersion"


# Release Routines:
[release.github_release]


# Other:
[git]
brew = "cole-wilson/homebrew-taps"
github = "cole-wilson/sailboat"


# Thank you for using Sailboat!