#            _  _  _                _   
#  ___ __ _ (_)| || |__  ___  __ _ | |_ 
# (_-</ _` || || || '_ \/ _ \/ _` ||  _|
# /__/\__,_||_||_||_.__/\___/\__,_| \__|
                                      
# Basic Setup:
_comments = true
name = "Sailboat"
short_name = "sailboat"
email = "cole@colewilson.xyz"
short_description = "A quick and easy way to distribute your Python projects!"
description = "Sailboat is a Python developer's best friend. It's a Python build tool that can do anything you need it to!"
url = "https://github.com/cole-wilson/sailboat"
keywords = "sail package python setup.py sailboat shipsnake distribute ship snake snek release build"
license = "MIT"
latest_build = "0.26.2"
author = "Cole Wilson"
latest_release = "0.26.0"
release-notes = "Update some stuff"


# Resource Setup:
[resources]
icon = ""
data_files = [ "resources/*", "plugins.json",]
modules = [ "toml", "semver", "requests", "setuptools", "twine", "colorama", "enlighten", "blessed",]
file = "__main__.py"
no_import = [ "shutil", "pathlib", "re", "os", "glob", "pkg_resources", "traceback", "json", "subprocess", "thismoduledoesntexistihope_fortesting_48927348", "stat",]


# Plugin Commands:
[command.tasks]


# Build Routines:
[build.homebrew]

[build.pyinstaller]
_run = false
type = 1
mac = true
windows = true
unix = true
bundle_id = "xyz.colewilson.sailboat"

[build.build_docs_readme]

[build.setcodeversion]

[build.actions]

[build.pypi.commands]
sail = "__main__.main"
ssail = "__main__.main"
sssail = "__main__.main"
ssssail = "__main__.main"
sailboat = "__main__.main"
ssailboat = "__main__.main"
sssailboat = "__main__.main"
ssssailboat = "__main__.main"

[build.pypi.entry_points.sailboat_plugins]
quickstart = "sailboat.core:QuickStart"
remove = "sailboat.core:Remove"
add = "sailboat.core:Add"
git = "sailboat.core:Git"
dev = "sailboat.core:Develop"
release = "sailboat.core:Release"
plugins = "sailboat.core:ManagePlugins"
wizard = "sailboat.core:Wizard"
build = "sailboat.build:Build"
pypi = "sailboat.builders:PyPi"
homebrew = "sailboat.builders:Homebrew"
pyinstaller = "sailboat.builders:PyInstaller"
actions = "sailboat.builders:Actions"
tasks = "sailboat.other:Tasks"
build_docs_readme = "sailboat.other:BuildDocs"
setcodeversion = "sailboat.other:SetVersion"


# Release Routines:
[release.github_release]


# Other:
[git]
brew = "cole-wilson/homebrew-taps"
github = "cole-wilson/sailboat"


# Thank you for using Sailboat!