name = "Sailboat"
short_name = "sailboat"
author = "Cole Wilson"
email = "cole@colewilson.xyz"
short_description = "A quick and easy way to package, freeze, and distribute your Python projects!"
description = ""
url = "https://github.com/cole-wilson/sailboat"
keywords = "ship distribute package snake python freeze shipsnake setuptools sailboat"
license = "MIT"
latest_build = "0.4.1+3e58592.1"

[resources]
icon = ""
data_files = [ "resources/*", "*.template", "*.template*", "*.txt",]
modules = [ "toml", "requests", "semver",]
file = "__main__.py"
no_import = [ "getopt", "glob", "re", "shutil", "os", "wheel", "PyInstaller", "twine", "dmgbuild",]

[build]
build_script = "extra.py"
actions_only = true
type = "1"
mac = true
unix = true
windows = true
installer = false
actions = true
bundle_id = "com.colewilson.sailboat"
homebrew = true
actions_built_latest = false
release_notes = ""

[git]
github = "cole-wilson/sailboat"
brew = "cole-wilson/homebrew-taps"

[extras]
licensed_files = [ "sailboat/prerelease.py", "sailboat/__init__.py", "sailboat/wizard.py", "sailboat/actions.py", "sailboat/release.py", "sailboat/__main__.py", "sailboat/git.py", "sailboat/build.py", "sailboat/task.py",]

[build.commands]
sail = "__main__.main"
sailboat = "__main__.main"
