remote_theme: pmarsceill/just-the-docs
logo: "https://www.pinclipart.com/picdir/big/383-3832964_im-on-a-boat-stamp-sailboat-stencil-clipart.png"
aux_links:
  "View on GitHub":
    - "//github.com/cole-wilson/sailboat"
color_scheme: light
ga_tracking: G-SNWXJHTKZD
